# environment.yml
name: ths_prediction
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - pandas=2.2
  - numpy=1.26
  - scikit-learn=1.4
  - matplotlib=3.8
  - seaborn=0.13
  - tqdm
  - scipy
  - joblib
  - pip
  - pip
  - pip:
    - xgboost==2.0.3
    - shap==0.48